add enterprise-openedx-operator permission checks
openedx/edx-enterprise-data pull request #116
Opened 2019-04-01 14:17 UTC by muhammad-ammar

[ENT-1738](https://openedx.atlassian.net/browse/ENT-1711)

2019-04-01 15:21 UTC, christopappas approved these changes
LGTM 👍

2019-04-01 16:44 UTC, brittneyexline commented on enterprise_data_roles/rules.py
> +        role_in_jwt, __, enterprise_id_in_jwt = role_data.partition(':')
we could probably refactor this check now to use the context checking functionality just added in edx-rbac

2019-04-01 17:49 UTC, muhammad-ammar commented on enterprise_data_roles/rules.py
> +        role_in_jwt, __, enterprise_id_in_jwt = role_data.partition(':')
will do in https://github.com/edx/edx-enterprise-data/pull/113 or in a separate future PR

2019-04-02 10:40 UTC, mushtaqak commented on enterprise_data_roles/constants.py
> +ENTERPRISE_OPERATOR_ROLE = 'enterprise_openedx_operator'
Should this be renamed to `SYSTEM_ENTERPRISE_OPERATOR_ROLE` to maintain consistency?

2019-04-02 13:03 UTC, mushtaqak commented on enterprise_data/tests/mixins.py
> +        role_data = '{system_wide_role}'.format(system_wide_role=system_wide_role)
an extra nit: can we use constant in method argument for `enterprise_admin`?

2019-04-02 14:26 UTC, muhammad-ammar commented
@brittneyexline Can we merge this?

2019-04-03 15:44 UTC, brittneyexline commented on enterprise_data_roles/rules.py
> +def request_user_has_operator_access(*args, **kwargs):  # pylint: disable=unused-argument
i'm hoping we can greatly simplify this predicate logic if we can get the rbac utils right. i think we'll want to implement the wildcard idea to help with this. the predicates here shouldn't have to dig into the jwt themselves to determine access - that is the whole purpose of the rbac package.

2019-04-03 15:44 UTC, brittneyexline commented on enterprise_data_roles/utils.py
> +def get_request_or_stub():
i'm pretty sure we have this function in edx-rbac, so there shouldn't be a need to copy, right? if you do need some adjustments, i'd rather see the edx-rbac function modified to meet your needs.

2019-04-03 19:58 UTC, christopappas commented on enterprise_data_roles/utils.py
> +def get_request_or_stub():
agreed. this is where it lives in edx-rbac (with the note that i might live in drf extensions in the future) - https://github.com/edx/edx-rbac/blob/master/edx_rbac/utils.py#L17

2019-04-03 20:01 UTC, christopappas requested changes
I believe we need to replace the get_request_or_stub function unless there is a need for it to be here as well as edx-rbac

2019-04-04 05:13 UTC, muhammad-ammar commented on enterprise_data_roles/utils.py
> +def get_request_or_stub():
I added this function here because of https://edx-internal.slack.com/archives/CDXAQ8G02/p1554212699018200

2019-04-04 15:43 UTC, christopappas commented on enterprise_data_roles/utils.py
> +def get_request_or_stub():
ah, well, he's not going to delete that on us, he's asked us to remove it before we're done iterating on edx-rbac, so i think it's fine to leave the call from edx-rbac for now. additionally, we wouldn't just want to paste it here. we'd want to move the stuff in edx-rbac in question to edx-drf-extensions and import from there

so yeah, i think it's fine to keep the import from edx-rbac for now, because we are the ones in charge of moving that code over to edx-drf-extensions

i'll file a ticket to refactor edx-rbac once things are more stabile

2019-04-04 18:23 UTC, muhammad-ammar commented on enterprise_data_roles/utils.py
> +def get_request_or_stub():
removed the new util and back to rbac get_request_or_stub

2019-04-04 18:28 UTC, christopappas approved these changes

2019-04-05 14:23 UTC, brittneyexline approved these changes
just one thing that needs to be changed before merging!

2019-04-05 14:23 UTC, brittneyexline commented on enterprise_data_roles/rules.py
> +        ALL_ACCESS_CONTEXT
we should pass in the request enterprise id here instead.

2019-04-06 19:46 UTC, merged