Ent 2033 include date report config
openedx/edx-enterprise-data pull request #151
Opened 2019-09-27 12:07 UTC by sameenfatima78

2019-09-27 12:07 UTC, edx-webhook commented
Thanks for the pull request, @sameenfatima78! I've created [OSPR-3859](https://openedx.atlassian.net/browse/OSPR-3859) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

2019-10-02 09:01 UTC, irfanuddinahmad requested changes

2019-10-02 09:01 UTC, irfanuddinahmad commented on enterprise_reporting/reporter.py
> +        if self.reporting_config['include_date']:
get() would be a safer choice here

2019-10-02 09:01 UTC, irfanuddinahmad commented on enterprise_reporting/send_enterprise_reports.py
> +
nit: Remove extra line

2019-10-02 09:01 UTC, irfanuddinahmad commented on enterprise_reporting/tests/utils.py
> +
nit: remove extra

2019-10-02 09:20 UTC, sameenfatima78 commented on enterprise_reporting/reporter.py
> +        if self.reporting_config['include_date']:
Agreed.

2019-10-03 12:20 UTC, muhammad-ammar requested changes

2019-10-03 12:20 UTC, muhammad-ammar commented on enterprise_reporting/tests/test_utils.py
> +        assert actual_file_name == expected_file_name
I think we convert both the tests into a single test like below

```python
@ddt.data(
    '_catalog_json_2019-09-30.json',
    '_catalog_json.json'
)
def test_compression_file_name(self, file_suffix):
        """
        Tests that files are compressed with the correct file name with and without date.
        """
        tf = tempfile.NamedTemporaryFile(suffix=file_suffix)
        tf.write(b'randomtext54321')
        actual_file_name = utils._get_compressed_file([tf])
        expected_file_name = tf.name.split('.json', 1)[0] + '.zip'
        assert actual_file_name == expected_file_name
```

2019-10-03 12:20 UTC, muhammad-ammar commented on enterprise_reporting/tests/test_reporter.py
> +		assert actual_file_name == expected_file_name
Can we also convert these two tests into single like I mentioned for other tests?

2019-10-03 12:20 UTC, muhammad-ammar commented on enterprise_reporting/reporter.py
> +            return "{dir}/{enterprise_id}_{data}_{ext}_{date}.{ext}".format(
one way to avoid repetition of same format string in `if...else` could be like below.
```python
date_str = "_{}".format(NOW) if include_date else "" 
return "{dir}/{enterprise_id}_{data}_{ext}{date_str}.{ext}".formatdir=self.FILE_WRITE_DIRECTORY,
    enterprise_id=self.enterprise_customer_uuid,
    data=self.data_type,
    date_str=date_str,
    ext=self.report_type,
)
```

2019-10-03 12:21 UTC, muhammad-ammar commented on enterprise_reporting/tests/test_reporter.py
> +			)
indentation is bit off here.

2019-12-16 12:36 UTC, closed without merging