ENT-1983 | Search for user in admin portal
openedx/edx-enterprise-data pull request #159
Opened 2019-12-12 13:29 UTC by HammadAhmadWaqas

added search_email param in enterprise enrollment API.

2020-01-23 09:07 UTC, ziafazal requested changes
@HammadAhmadWaqas One change I suggested.

2020-01-23 09:07 UTC, ziafazal commented on enterprise_data/api/v0/views.py
> +            queryset = queryset.filter(user_email__icontains=search_email)
I think this should be exact match instead of partial match

2020-01-24 14:27 UTC, HammadAhmadWaqas commented on enterprise_data/api/v0/views.py
> +            queryset = queryset.filter(user_email__icontains=search_email)
@ziafazal  As discussed in the meeting, a partial match is more feasible here.

2020-01-28 10:51 UTC, ziafazal approved these changes

2020-01-28 14:17 UTC, georgebabey approved these changes

2020-01-29 11:28 UTC, merged