Add course title and start date filtering
openedx/edx-enterprise-data pull request #206
Opened 2020-07-22 20:08 UTC by raq929

Backend support for ENT-3086.
Adds filtering and tests.

2020-07-27 21:28 UTC, taliaedX requested changes
So the actual query part in the views is a-okay.

The tests are where I might be losing my mind.
The structure seems a bit odd and there's some spots where it may be obvious (or I may be losing my mind) what is off and others where I'm not entirely sure, but it might help if we can chat over what the intended test cases are and what data is absolutely necessary for them to make sure I can either understand the existing test structure or help figure out something maybe more efficient.

2020-07-27 21:28 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +                course_start=course_start_dates[0],
I'm confused. Why are you looping through this `course_start_dates` list making an EnterpriseEnrollmentFactory object and then manually appending each element from the course_start_date list outside of this forloop? I'm guessing because different enterprise user objects, but it seems like two different implementations are being used here (loop vs manual index fetching in the list)

Did you intend to do something like (I put enterprise_users in a list because a nested loop here just seems appropriate for a change):

```
enterprise_users = [enterprise_user0, enterprise_user1, enterprise_user2]
for start_date in course_start_dates:
    for user in enterprise_users:
        EnterpriseEnrollmentFactory(
            enterprise_user=user,
            enterprise_id=self.enterprise_id,
            course_start=start_date,
        )
```

2020-07-27 21:28 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +            assert pytz.utc.localize(datetime.strptime(result["course_start"], "%Y-%m-%dT%H:%M:%SZ")) \
what is the purpose of localization here?

2020-07-27 21:28 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +            pytz.utc.localize(datetime(2020, 9, 30)),
I went backwards with this, but why localize here. Are you just trying to get a datetime that actually includes timezone? Or the opposite?

2020-07-27 21:28 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +        EnterpriseEnrollmentFactory(
again I feel like this wasn't supposed to be outside this loop but I may be taking crazy pills.

2020-07-27 21:28 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +        enrollments = EnterpriseEnrollment.objects.filter(**search_kwargs)
The whole structure of this test feels odd to me, but not sure how to pin it down to one specific thing. The fact you are basically having to copy the logic out the `apply_filters` function feels very weird to me. There's a lot of looping here as well and I wonder if perhaps either the ddt data parameters should be a bit more extensive or if we can consolidate data down to some static vars.

2020-07-27 21:40 UTC, raq929 commented on enterprise_data/tests/test_views.py
> +            pytz.utc.localize(datetime(2020, 9, 30)),
The purpose of localization is not getting an warning every time I make an enrollment. 😉

2020-07-27 21:41 UTC, raq929 commented on enterprise_data/tests/test_views.py
> +        EnterpriseEnrollmentFactory(
No, it is. _Sigh_. I'm not in love with this.

2020-07-27 21:41 UTC, raq929 commented on enterprise_data/tests/test_views.py
> +        enrollments = EnterpriseEnrollment.objects.filter(**search_kwargs)
Yeah. Let's chat tomorrow morning and see what we come up with. 
I don't love the copying the logic either; it's something I borrowed from other tests in this test suite, but I agree it does not give me a good feeling.

2020-07-27 21:43 UTC, raq929 commented on enterprise_data/tests/test_views.py
> +                course_start=course_start_dates[0],
I wanted to be sure I have enrollments for each of my course titles/ start dates/ emails, and one thing that has some of those things again. To be sure that it works with more than one enrollment.
You're not losing your mind, these tests are kind of based on other tests in this test suite, but have requirements that went beyond the ability of that structure to handle it.

2020-07-28 14:15 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +            pytz.utc.localize(datetime(2020, 9, 30)),
Now I'm just curious what warning was happening lol

2020-07-28 15:50 UTC, taliaedX approved these changes
So per our call, this is definitely a bit neater and makes the test cases a bit clearer. We could still use a little info on why the total expected enrollment counts are as such whether that be in each individual test or commented with the data. But it's definitely a lot nicer and as before is quite thorough, so definitely mergeable!

2020-07-28 15:50 UTC, taliaedX commented on enterprise_data/tests/test_views.py
> +        # import pdb; pdb.set_trace()
I know you saw it on the call, but just to doubly make sure that this gets removed. :p

2020-07-28 17:01 UTC, raq929 commented on enterprise_data/tests/test_views.py
> +            pytz.utc.localize(datetime(2020, 9, 30)),
A very large annoying one about how I gave Django a native datetime when I ought to have used a timezone blah blah blah

2020-07-28 17:02 UTC, merged