WIP - ENT-788 New django app for enterprise-data
openedx/edx-enterprise-data pull request #23
Opened 2018-02-16 16:50 UTC by georgebabey

2018-02-28 20:15 UTC, brittneyexline reviewed
looks good overall, and thanks for putting in all the work to get CI in place 👍

2018-02-28 20:15 UTC, brittneyexline commented on enterprise_data/migrations/0001_initial.py
> +from __future__ import unicode_literals
what is the purpose of adding the empty management command file above?

2018-02-28 20:15 UTC, brittneyexline commented on enterprise_data/migrations/0005_auto_20180216_1053.py
> +from django.db import migrations, models
any reason not to consolidate these migrations by removing them and then generating one migration that initializes the table as we want?

2018-02-28 20:15 UTC, brittneyexline commented on enterprise_data/permissions.py
> +        print(enterprise_learner_data)
use a logger here and below if you intend to keep these.

2018-02-28 20:15 UTC, brittneyexline commented on enterprise_data/urls.py
> +the `urlpatterns` list routes urls to views. for more information please see:
not sure if this documentation is relevant to the project, seems generic to django?

2018-02-28 20:15 UTC, brittneyexline commented on enterprise_data/api/v0/views.py
> +        return EnterpriseEnrollment.objects.filter(enterprise_id=enterprise_id)
i think we will also need to filter on consent granted = 1 if the request isn't from a staff user - maybe that's something that could be implemented using a filter class?

2018-02-28 20:38 UTC, georgebabey commented on enterprise_data/api/v0/views.py
> +        return EnterpriseEnrollment.objects.filter(enterprise_id=enterprise_id)
Good catch! Should we filter that out regardless of staff?

2018-02-28 20:39 UTC, georgebabey commented on enterprise_data/migrations/0001_initial.py
> +from __future__ import unicode_literals
Was an initial attempt before i discovered fixtures are built-in. Will remove

2018-02-28 20:39 UTC, georgebabey commented on enterprise_data/migrations/0005_auto_20180216_1053.py
> +from django.db import migrations, models
Yes, will squash the migrations (its in the TODO in the description)

2018-02-28 21:09 UTC, georgebabey commented
@douglashall A few more unit tests to write and need to squash the migrations, but otherwise I think this is good to go. Can i get some 👀 ?

2018-02-28 21:28 UTC, douglashall requested changes
Can we test this on a sandbox?

2018-02-28 21:28 UTC, douglashall commented on MANIFEST.in
> +recursive-include requirements *.txt
The red symbol at the end of this line indicates that you are missing a newline at the end on the last line in this file.

See https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline.

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/api/v0/views.py
> +        return EnterpriseEnrollment.objects.filter(enterprise_id=enterprise_id)
Yes, probably best to lock it down until we need to open it up.

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/clients.py
> +            response = response = endpoint.get(**querystring)
Typo.

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/clients.py
> +        if not response['results'] or response['count'] != 1:
Would it be better to raise an exception if you get more than one result instead of just returning `None`?

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/fixtures/enterprise_enrollment.json
> +[
The undocumented edX standard is to use factories instead of fixtures. See https://github.com/edx/edx-enterprise/blob/master/test_utils/factories.py.

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/migrations/0002_auto_20180209_1444.py
> +    ]
Should we have migrations here if the table is created by the analytics pipeline? How do we handle this situation in edx-analytics-data-api for other models?

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/permissions.py
> +    the token
Missing period. :)

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/permissions.py
> +            request.session['enterprise_id'] = self.get_user_enterprise_id(request.auth, request.user)
Is this the right place for this? Seems like it would be better as middleware.

2018-02-28 21:28 UTC, douglashall commented on enterprise_data/permissions.py
> +        return request.session['enterprise_id'] == enterprise_in_url
You should log when this is false.

2018-02-28 21:30 UTC, douglashall commented
I don't see a test that hits the endpoint? Am I missing it?

2018-02-28 21:40 UTC, douglashall commented
Also, looks like you need to resolve a conflict.

2018-02-28 21:58 UTC, georgebabey commented on enterprise_data/clients.py
> +        if not response['results'] or response['count'] != 1:
Sure, I can do that and handle the exception in the permission that calls this 👍

2018-02-28 21:59 UTC, georgebabey commented on enterprise_data/fixtures/enterprise_enrollment.json
> +[
Is there reason behind this? Given that Django makes it very easy to use fixtures to load the fixture data as well as use it in tests, rolling our own seems like a lot of unnecessary overhead.

FWIW The analytics-data-api where this installs to uses fixtures for test data.

2018-02-28 22:05 UTC, georgebabey commented on enterprise_data/migrations/0002_auto_20180209_1444.py
> +    ]
analytics-data-api uses `--run-syncdb` to generate the db schema. Guidance from django is to use migrations:

> --run-syncdb. New in Django 1.9. Allows creating tables for apps without migrations. While this isn’t recommended, the migrations framework is sometimes too slow on large projects with hundreds of models.

Speed is not of concern for us. I suspect analytics-data-api predates the builtin migration framework

2018-02-28 22:06 UTC, georgebabey commented on enterprise_data/permissions.py
> +            request.session['enterprise_id'] = self.get_user_enterprise_id(request.auth, request.user)
The problem with middleware is it would be on every request when we really only need this for the permission check. Ideal solution is putting the enterprise on the JWT as a scope and avoid the roundtrip all together. Will need to circle back to this once scopes lands.

2018-02-28 22:10 UTC, douglashall commented on enterprise_data/migrations/0002_auto_20180209_1444.py
> +    ]
What I mean is, edx-analytics-data-api is a bit different from a normal Django project because the analytics pipeline is the thing that publishes to the mysql database that backs it. Do we run migrations as a part of the edx-analytics-data-api deployment process?

2018-03-05 19:21 UTC, georgebabey commented
@douglashall Updated based on your review and working to get it onto the sandbox. 

The two comments I didn't address were:
- Still using fixtures for data load and testing (matching what is done in data-api)
- Enterprise lookup done in permission instead of middleware (see comment above)

2018-03-05 20:25 UTC, brittneyexline approved these changes

2018-03-05 20:54 UTC, douglashall commented
Why don't we see the codecov checks in the list of all checks that have passed?

2018-03-05 21:02 UTC, georgebabey commented
@douglashall Might be because there is no baseline report.

2018-03-05 21:05 UTC, douglashall approved these changes
It would be good to add something to the README file which talks about how this repository is used in relation to edx-analytics-data-api.

Reminder to squash commits.

2018-03-07 12:31 UTC, merged