FC-0001: Remove EdxRestApiClient usage in edx-enterprise-data
openedx/edx-enterprise-data pull request #300
Opened 2022-04-18 15:35 UTC by UvgenGen

https://github.com/openedx/public-engineering/issues/41
**Merge checklist:**
- [ ] [Version](https://github.com/edx/edx-enterprise-data/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/edx/edx-enterprise-data/blob/master/CHANGELOG.rst) record added

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/edx/edx-enterprise-data/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [Travis](https://travis-ci.org/github/edx/edx-enterprise-data), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise-data/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-analytics-data-api](https://github.com/edx/edx-analytics-data-api) to upgrade dependencies (including edx-enterprise-data)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-analytics-data-api will look for the latest version in PyPi.
    - Note: the edx-enterprise-data constraint in edx-analytics-data-api **must** also be bumped to the latest version in PyPi.

2022-04-18 15:35 UTC, openedx-webhooks commented
Thanks for the pull request, @UvgenGen! I've created [OSPR-6626](https://openedx.atlassian.net/browse/OSPR-6626) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-04-27 15:56 UTC, natabene commented
@UvgenGen Thank you for your contribution. Is this ready for our review?

2022-05-02 09:08 UTC, UvgenGen commented
@natabene yes, this is ready for review.

2022-05-03 15:10 UTC, dianakhuang commented
@UvgenGen I'm working on reviewing it right now, but it seems like there's some quality fixes and a rebase to fix conflicts that will need to happen before I can merge it.

2022-05-03 15:23 UTC, dianakhuang reviewed
This looks good to me overall, but the quality/test fixes and conflict resolution still need to happen.

2022-05-06 13:40 UTC, UvgenGen commented
@dianakhuang  the quality/test fixed and conflict resolved)

2022-05-17 20:13 UTC, idegtiarov commented
@UvgenGen please resolve conflicts in this PR as well

2022-05-20 19:33 UTC, muhammad-ammar requested changes
I am done with first pass of the review. Let me know once you are done with addressing the feedback. 

Multiple services in edX are dependent on this repo and its clients. Can you share how did you test the code other than unit tests?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
>          self.client_secret = client_secret or os.environ.get('LMS_OAUTH_SECRET')
Are `LMS_OAUTH_KEY` and `LMS_OAUTH_SECRET` same as `settings.BACKEND_SERVICE_EDX_OAUTH2_KEY`,
`settings.BACKEND_SERVICE_EDX_OAUTH2_SECRET`?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
> +            timeout=(3.1, 5)
can you explain what are these values?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
> +        response = requests.post(
can [get_oauth_access_token](https://github.com/openedx/edx-rest-api-client/blob/47603fdf58dd54139e448756998cff483f463c40/edx_rest_api_client/client.py#L73)  be used in place of this `post` request?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
>  class EdxOAuth2APIClient:
can this client be implemented like `EnterpriseApiClient` above?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
> +        path = f"{resource}{'/' + resource_id if resource_id else ''}{'/' + detail_resource if detail_resource else ''}"
It is hard to understand this one liner? Can we make it readable?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/enterprise.py
> +    API_BASE_URL = urljoin(os.getenv('ANALYTICS_API_URL', default='') + '/', 'enterprise/api/v0')
can you share the reason for using `urljoin` here and at other places?

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_data/clients.py
>      (https://github.com/edx/edx-rest-api-client).
docstring needs to be updated.

2022-05-20 19:33 UTC, muhammad-ammar commented on enterprise_reporting/clients/__init__.py
> +        data = response.json()
I think it would be better to extract this piece of into a method on client and then use here and in `traverse_pagination`.

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
>          self.client_secret = client_secret or os.environ.get('LMS_OAUTH_SECRET')
Yes, it's the same.

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/enterprise.py
> +    API_BASE_URL = urljoin(os.getenv('ANALYTICS_API_URL', default='') + '/', 'enterprise/api/v0')
We use urljoin to avoid incorrect url due to wrong trailing slash.

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +            timeout=(3.1, 5)
I just do request as in https://github.com/openedx/edx-rest-api-client/blob/adeb9df7f1f8f52532a5bdd5faa6e3e400a02ef1/edx_rest_api_client/client.py#L73
definition in edx-rest-api-client:
https://github.com/openedx/edx-rest-api-client/blob/adeb9df7f1f8f52532a5bdd5faa6e3e400a02ef1/edx_rest_api_client/client.py#L22

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +        response = requests.post(
Yes, we can use [get_oauth_access_token](https://github.com/openedx/edx-rest-api-client/blob/47603fdf58dd54139e448756998cff483f463c40/edx_rest_api_client/client.py#L73) Thank you) 
Updated

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +        path = f"{resource}{'/' + resource_id if resource_id else ''}{'/' + detail_resource if detail_resource else ''}"
Updated

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
>  class EdxOAuth2APIClient:
we cannot inherit from a class OAuthAPIClient for EdxOAuth2APIClient because this client use in scripts and OAuthAPIClient required some settings for work.

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_data/clients.py
>      (https://github.com/edx/edx-rest-api-client).
Updated

2022-05-24 11:51 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +        data = response.json()
updated

2022-05-24 11:55 UTC, UvgenGen commented
@muhammad-ammar @dianakhuang 
`Can you share how did you test the code other than unit tests?`
I'm just checking that the requests are successful. We discussed that testing will be done on the tcril side.

2022-06-21 14:11 UTC, dianakhuang commented
@UvgenGen could you rebase this PR for the second round of review? I'll poke the team for testing and review again.

2022-06-21 15:50 UTC, UvgenGen commented
@dianakhuang rebased)

2022-06-23 10:22 UTC, zamanafzal requested changes

2022-06-23 10:22 UTC, zamanafzal commented on enterprise_reporting/clients/__init__.py
> +    def traverse_pagination(self, response, url):
In a few places, the `response` is changed to `data` and in some other places, it is not. Like here, traverse_pagination() you used `response` but when you are calling it passing it as `data`. Can we please stick to the one naming convention as it was before?

2022-06-23 10:22 UTC, zamanafzal commented on enterprise_data/clients.py
> +        except (RequestException) as exc:
I think we should catch the `HTTPError` exception as well and add the Logs for that.

2022-06-23 10:22 UTC, zamanafzal commented on enterprise_data/tests/test_clients.py
> +            settings.BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL,
Do you expect that these values will be picked from the `[repo](https://github.com/openedx/edx-analytics-data-api)`?

2022-06-23 11:47 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +    def traverse_pagination(self, response, url):
updated

2022-06-23 11:47 UTC, UvgenGen commented on enterprise_data/clients.py
> +        except (RequestException) as exc:
I thought about it, but HTTPError inherits RequestException. So do we need to process both errors differently?

2022-06-23 11:49 UTC, UvgenGen commented on enterprise_data/tests/test_clients.py
> +            settings.BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL,
Yes, I expect it.

2022-06-23 12:02 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +    def traverse_pagination(self, response, url):
updated

2022-06-23 16:00 UTC, irfanuddinahmad commented on enterprise_data/__init__.py
> +__version__ = "4.3.2"
This should be a minor/major release number

2022-06-23 16:00 UTC, irfanuddinahmad commented on enterprise_reporting/clients/__init__.py
> +        response.raise_for_status()
Do we need to handle the HTTPError here?

2022-06-23 18:51 UTC, zamanafzal commented on enterprise_data/clients.py
> +        except (RequestException) as exc:
I think it is good to catch HTTPError separately and add the logs against it. It'll help to trace back the issue more quickly if arises.

2022-06-24 10:21 UTC, UvgenGen commented on enterprise_data/__init__.py
> +__version__ = "4.3.2"
Updated

2022-06-24 10:23 UTC, UvgenGen commented on enterprise_data/clients.py
> +        except (RequestException) as exc:
Updated

2022-06-24 10:29 UTC, UvgenGen commented on enterprise_reporting/clients/__init__.py
> +        response.raise_for_status()
I think we don’t. Or just logging some basic error message for all the APIs that can be used here.

2022-06-27 10:01 UTC, zamanafzal approved these changes
@UvgenGen Changes looks good to me.

2022-06-27 10:16 UTC, muhammad-ammar approved these changes
LGTM 👍

2022-06-27 11:20 UTC, zamanafzal commented
@dianakhuang  I think we are good to merge the PR once the codecov/patch job turns green. @UvgenGen Could you please fix it?

2022-06-28 07:58 UTC, UvgenGen commented
@zamanafzal tests updated. Could you run checkers please?

2022-06-28 14:14 UTC, dianakhuang commented
@UvgenGen unfortunately, there's still at least one failing test.

2022-06-28 19:28 UTC, UvgenGen commented
@dianakhuang  oh,`enterprise_reporting` takes requirements from `test-reporting.txt`. Requirements updated. Could you run checkers again please?

2022-06-28 20:19 UTC, dianakhuang commented
Sorry @UvgenGen , still seeing errors in the tests right now. (Seems to be in the settings?)

2022-06-29 15:28 UTC, UvgenGen commented
@dianakhuang I updated test setup and now it should work)

2022-06-29 16:09 UTC, UvgenGen commented
@dianakhuang it seems that the enterprise_reporting dir is ignored when coverage starts

2022-06-29 16:16 UTC, UvgenGen commented
As i see Run Coverage use django32-data env, and tox run tests with `--ignore enterprise_reporting/`
https://github.com/openedx/edx-enterprise-data/pull/300/files#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R45

2022-06-30 17:26 UTC, merged

2022-06-30 17:26 UTC, openedx-webhooks commented
@UvgenGen 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-enterprise-data&entry.867055334=https://github.com/openedx/edx-enterprise-data/pull/300&entry.1484655318=https://github.com/UvgenGen&entry.752974735=2022-04-18+15:35&entry.1917517419=2022-06-30+17:26&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->