FC-0001: Remove enterprise_catalogs API usages
openedx/edx-enterprise-data pull request #313
Opened 2022-06-13 15:46 UTC by ruzniaievdm

closes https://github.com/openedx/public-engineering/issues/61

## Description:

Replace this [usage](https://github.com/openedx/edx-enterprise-data/blob/9d2358c21ab8c14971a17e38737b46998ec390b9/enterprise_reporting/clients/enterprise.py#L123) with corresponding to the enterprise-catalog service

2022-06-13 15:46 UTC, openedx-webhooks commented
Thanks for the pull request, @ruzniaievdm! I've created [OSPR-6794](https://openedx.atlassian.net/browse/OSPR-6794) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.




<!-- comment:external_pr -->
<!-- jenkins ok to test -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-06-16 17:59 UTC, dianakhuang approved these changes
I think this looks good to me.

2022-06-16 17:59 UTC, dianakhuang commented on enterprise_reporting/clients/enterprise.py
> -    def get_content_metadata(self, enterprise_customer_uuid, reporting_config):
Huh, was this endpoint just unused?

2022-06-16 18:47 UTC, ruzniaievdm commented on enterprise_reporting/clients/enterprise.py
> -    def get_content_metadata(self, enterprise_customer_uuid, reporting_config):
This method previously called to `EnterpriseCustomerCatalogViewSet` of edx-enterpise. Since we're deleting this endpoint, we don't need it anymore.

2022-07-12 15:45 UTC, feanil requested changes
@ruzniaievdm it looks like the previous upgrade from the old RestApiClient introduced a bug where the base EdxOauth2ApiClient no longer honors the `APPEND_SLASH` setting.  Can you fix that here since, the new API endpoint does indeed expect a trailing slash?

2022-07-12 15:45 UTC, feanil commented on enterprise_reporting/clients/enterprise.py
> +            self.ENTERPRISE_CATALOGS_ENDPOINT,
Looking at https://github.com/openedx/enterprise-catalog/blob/28b007499e44569ecd1f6df50390d137cdf68f91/enterprise_catalog/apps/api/v1/urls.py#L44 it looks like the underlying implementation expects a trailing slash.   However, [looking at the parent class](https://github.com/openedx/edx-enterprise-data/blob/master/enterprise_reporting/clients/__init__.py#L23), it looks like while there is an `APPEND_SLASH` attribute, it's not no longer being referenced.

2022-07-29 09:25 UTC, ruzniaievdm commented
@feanil made a separate commit, after your approval I will rebase into one commit and then merge

2022-07-29 13:49 UTC, feanil approved these changes
This looks good to me.  @natabene can you schedule this for review by the relevant team.

2022-07-29 14:06 UTC, ruzniaievdm commented
@feanil Rebased to one commit and also removed two tests with unused endpoint variable `ENTERPRISE_CUSTOMER_CATALOGS_ENDPOINT`

2022-10-27 12:39 UTC, irfanuddinahmad requested changes
PR has coverage issues. Tests need to be added.

2022-10-27 12:39 UTC, irfanuddinahmad commented on enterprise_reporting/tests/test_clients.py
> -    def test_get_customer_catalogs(self, mock_get_oauth_access_token):
We should add the the "enterprise-catalogs" version of these tests

2022-10-28 10:36 UTC, HammadAhmadWaqas commented on enterprise_reporting/clients/__init__.py
> +    API_BASE_URL = urljoin(LMS_ROOT_URL, '/api')
No need to pass forward slash with `'/api'` instead we can just white 
`API_BASE_URL = urljoin(LMS_ROOT_URL, 'api')`

2022-10-28 10:36 UTC, HammadAhmadWaqas commented on enterprise_reporting/clients/__init__.py
> +        return urljoin(f"{self.API_BASE_URL}/", path)
here as well, `return urljoin(self.API_BASE_URL, path)` should be enough

2022-10-28 10:36 UTC, HammadAhmadWaqas commented on enterprise_reporting/clients/enterprise.py
> +    API_BASE_URL = urljoin(EdxOAuth2APIClient.LMS_ROOT_URL + '/', 'enterprise/api/v1')
`urljoin(EdxOAuth2APIClient.LMS_ROOT_URL + 'enterprise/api/v1')` should be enough

2022-11-01 15:16 UTC, mphilbrick211 commented
@HammadAhmadWaqas @dianakhuang do you need Raccoon Gang to do anything with the requested changes, or will you be handling internally?

2022-12-02 07:50 UTC, awais786 commented
https://github.com/openedx/edx-enterprise-data/pull/345 I have cherry-pick the commit in new PR.

2023-01-20 21:20 UTC, e0d commented
@awais786 has this PR been taken over, should this be closed?

2023-01-23 06:51 UTC, awais786 commented
@e0d This [PR](https://github.com/openedx/edx-enterprise-data/pull/345) merged and deployed. We can close this.

2023-01-23 06:51 UTC, closed without merging

2023-01-23 06:51 UTC, openedx-webhooks commented
@ruzniaievdm Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/edx-enterprise-data&entry.867055334=https://github.com/openedx/edx-enterprise-data/pull/313&entry.1484655318=https://github.com/ruzniaievdm&entry.752974735=2022-06-13+15:46&entry.1917517419=2023-01-23+06:51&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->