ENT-978 Update enterprise enrollment api with user country code and l…
openedx/edx-enterprise-data pull request #35
Opened 2018-05-15 13:20 UTC by zubair-arbi

…ast activity date

@asadiqbal08 @saleem-latif @irfanuddinahmad @muhammad-ammar 
Related edx-analytics-pipeline PR: https://github.com/edx/edx-analytics-pipeline/pull/504

2018-05-16 02:30 UTC, georgebabey requested changes
As mentioned in the pipeline PR, we should change the field to `last_activity_timestamp` to match the other datetime fields

2018-05-16 13:28 UTC, UmanShahzad commented
@zubair-arbi BTW tests are failing because of `caniusepython3==6.0.0`. After running `make upgrade` successfully (which I did in #34), tests should pass.

2018-05-21 19:40 UTC, georgebabey approved these changes

2018-06-12 10:11 UTC, merged

2018-06-12 10:56 UTC, zubair-arbi commented
@georgebabey I forgot to change to name of field `last_activity_date` from `last_acitivity_timestamp` in this PR. So I have addressed this in a separate PR https://github.com/edx/edx-enterprise-data/pull/39 and merged it.