feat: endpoint to get skills aggregated data for an enterprise customer
openedx/edx-enterprise-data pull request #473
Opened 2024-08-05 14:55 UTC by jajjibhai008

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-analytics-data-api doesn't install it
    - `test-master.in` if edx-analytics-data-api pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the edx-analytics-data-api requirements installed or if you checked out edx-enterprise-data into the src directory used by edx-analytics-data-api, you can run this command through an edx-analytics-data-api shell.
        - It would be `./manage.py makemigrations` in the shell.
- [ ] [Version](https://github.com/openedx/edx-enterprise-data/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/openedx/edx-enterprise-data/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/edx-enterprise-data/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [Travis](https://travis-ci.org/github/edx/edx-enterprise-data), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise-data/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-analytics-data-api](https://github.com/openedx/edx-analytics-data-api) to upgrade dependencies (including edx-enterprise-data)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-analytics-data-api will look for the latest version in PyPi.
    - Note: the edx-enterprise-data constraint in edx-analytics-data-api **must** also be bumped to the latest version in PyPi.

2024-08-06 07:43 UTC, jajjibhai008 commented on enterprise_data/admin_analytics/database.py
> +def get_db_connection(database='default'):
Ignore this change while reviewing the PR.

2024-08-06 10:51 UTC, saleem-latif requested changes

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/data_loaders.py
> +    enterprise_uuid = enterprise_uuid.replace("-", "")
nit: Use single quotes `'` for all strings. Please do this for all the strings in the PR.

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/database.py
> +def get_db_connection(database='default'):
Okay, but make sure to revert it before merging.

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    Get the skills data for the bubble chart.
nit: Please update the doc string with `Arguments` and `Returns`

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    skills_filtered = date_filter(start=start_date, end=end_date, data_frame=skills_filtered, date_column="date")
nit: You can skip above variable definition by doing

```
 skills_filtered = date_filter(
    start=start_date,
    end=end_date,
    data_frame=skills.copy(),
    date_column='date',
)

```

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +def skills_bubble_chart_df(start_date, end_date, skills):
nit: Maybe rename to `get_skills_bubble_chart_data`

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +def top_skills_enrollment(start_date, end_date, skills):
nit: please rename to `get_top_skills_enrollment_data`.

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    Get the top skills by enrolls.
nit: Please update the doc string with `Arguments` and `Returns`

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    skills_filtered = date_filter(start=start_date, end=end_date, data_frame=skills_filtered, date_column="date")
Same as above.

```
 skills_filtered = date_filter(
    start=start_date,
    end=end_date,
    data_frame=skills.copy(),
    date_column='date',
)

```

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +def top_skills_completion(start_date, end_date, skills):
Idea: Maybe create a single function named `get_skills_chart_data(chart_type, start_data, end_date, skills)` where `chart_type` is an enum containing `bubble_chart, top_skills_enrollment_chart, top_skills_completion_chart`.

This function can perform the operation common to all functions i.e.
```
 skills_filtered = date_filter(start=start_date, end=end_date, data_frame=skills_filtered, date_column="date")
```
and pass the filtered skills data to the rest of the individual functions (i.e. `get_skills_bubble_chart_data`) that will be called based on `chart_type`.

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    Get the top skills by completions.
nit: Please update the doc string with `Arguments` and `Returns`

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    Get the top skills data for the CSV download.
nit: Please update the doc string with `Arguments` and `Returns`

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/api/v1/views/enterprise_admin.py
> -            learner_progress = EnterpriseAdminLearnerProgress.objects.get(enterprise_customer_uuid=enterprise_id)
Question: What was the reason for this change?

2024-08-06 10:51 UTC, saleem-latif commented on enterprise_data/api/v1/views/enterprise_admin.py
> +        HTTP GET endpoint to retrieve the enterprise admin skills aggregated data.
nit: Please update the doc string with `Arguments` and `Returns`

2024-08-06 15:16 UTC, jajjibhai008 commented on enterprise_data/api/v1/views/enterprise_admin.py
> -            learner_progress = EnterpriseAdminLearnerProgress.objects.get(enterprise_customer_uuid=enterprise_id)
> Question: What was the reason for this change?

Just run the black formatter and this formatting happens.

2024-08-06 15:36 UTC, jajjibhai008 commented on enterprise_data/admin_analytics/utils.py
> +def top_skills_completion(start_date, end_date, skills):
I have followed the existing pattern to distinguish the functionality clearly. Merging the code of all three functions could create a mess and be less readable. So that's why I follow this pattern

2024-08-07 08:02 UTC, saleem-latif requested changes

2024-08-07 08:02 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +def top_skills_completion(start_date, end_date, skills):
No, I am not asking to merge the code. I am asking to create  a new function. Something like the following

```
class ChartType(enum.Enum):
    """
    Chart types.
    """
    BUBBLE = 'bubble'
    TOP_SKILLS_ENROLLMENT = 'top_skills_enrollment'
    TOP_SKILLS_COMPLETION = 'top_skills_completion'


def get_skills_chart_data(chart_type, start_date, end_date, skills):
    """
    Get chart data for skill charts.

    Arguments:
        chart_type (ChartType): The type of chart to generate.
        start_date (datetime): The start date for the date filter.
        end_date (datetime): The end date for the date filter.
        skills (pandas.DataFrame): The skills data.
    """

    # Filter data based on the provided date range
    skills_filtered = date_filter(start=start_date, end=end_date, data_frame=skills.copy(), date_column="date")

    if chart_type == ChartType.BUBBLE:
        return get_skills_bubble_chart_df(skills=skills_filtered)
    elif chart_type == ChartType.TOP_SKILLS_ENROLLMENT:
        return top_skills_enrollment(skills=skills_filtered)
    elif chart_type == ChartType.TOP_SKILLS_COMPLETION:
        return top_skills_completion(skills=skills_filtered)


```

2024-08-07 11:14 UTC, saleem-latif approved these changes

2024-08-07 11:14 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +        end_date (str): The end date for the date filter.
nit: Please remove `start_date` and `end_date` from the doc string of all functions that do not accept these parameters

2024-08-07 11:14 UTC, saleem-latif commented on enterprise_data/admin_analytics/utils.py
> +    top_skills = (
Nice 👏🏼

2024-08-09 08:05 UTC, merged