feat: add flex-group filtering
openedx/edx-enterprise-data pull request #550
Opened 2024-12-23 13:14 UTC by omar-sarfraz

**Merge checklist:**
- [ ] Any new requirements are in the right place (do **not** manually modify the `requirements/*.txt` files)
    - `base.in` if needed in production but edx-analytics-data-api doesn't install it
    - `test-master.in` if edx-analytics-data-api pins it, with a matching version
    - `make upgrade && make requirements` have been run to regenerate requirements
- [ ] `make static` has been run to update webpack bundling if any static content was updated
- [ ] `./manage.py makemigrations` has been run
    - Checkout the [Database Migration](https://openedx.atlassian.net/wiki/spaces/AC/pages/23003228/Everything+About+Database+Migrations) Confluence page for helpful tips on creating migrations.
    - *Note*: This **must** be run if you modified any models.
      - It may or may not make a migration depending on exactly what you modified, but it should still be run.
    - This should be run from either a venv with all the edx-analytics-data-api requirements installed or if you checked out edx-enterprise-data into the src directory used by edx-analytics-data-api, you can run this command through an edx-analytics-data-api shell.
        - It would be `./manage.py makemigrations` in the shell.
- [ ] [Version](https://github.com/openedx/edx-enterprise-data/blob/master/enterprise/__init__.py) bumped
- [ ] [Changelog](https://github.com/openedx/edx-enterprise-data/blob/master/CHANGELOG.rst) record added
- [ ] Translations updated (see docs/internationalization.rst but also this isn't blocking for merge atm)

**Post merge:**
- [ ] Tag pushed and a new [version](https://github.com/openedx/edx-enterprise-data/releases) released
    - *Note*: Assets will be added automatically. You just need to provide a tag (should match your version number) and title and description.
- [ ] After versioned build finishes in [Travis](https://travis-ci.org/github/edx/edx-enterprise-data), verify version has been pushed to [PyPI](https://pypi.org/project/edx-enterprise-data/)
    - Each step in the release build has a condition flag that checks if the rest of the steps are done and if so will deploy to PyPi.
    (so basically once your build finishes, after maybe a minute you should see the new version in PyPi automatically (on refresh))
- [ ] PR created in [edx-analytics-data-api](https://github.com/openedx/edx-analytics-data-api) to upgrade dependencies (including edx-enterprise-data)
    - This **must** be done after the version is visible in PyPi as `make upgrade` in edx-analytics-data-api will look for the latest version in PyPi.
    - Note: the edx-enterprise-data constraint in edx-analytics-data-api **must** also be bumped to the latest version in PyPi.

2024-12-24 10:07 UTC, saleem-latif approved these changes

2024-12-26 12:32 UTC, irfanuddinahmad commented on enterprise_data/api/v1/urls.py
> +        fr'^enterprise/(?P<enterprise_uuid>{UUID4_REGEX})/segments',
Should we call this enterprise-groups?

2024-12-26 12:53 UTC, irfanuddinahmad requested changes

2024-12-26 12:53 UTC, irfanuddinahmad commented on enterprise_data/api/v1/views/enterprise_admin.py
> +    View for getting Group Memberships and Budgets information for an enterprise.
I think this view should be called enterpriseGroupMembershipView

2024-12-26 12:53 UTC, irfanuddinahmad commented on enterprise_data/api/v1/views/enterprise_admin.py
> +        budgets = EnterpriseSubsidyBudget.objects.filter(
Why are we combining both groups and budgets?

2024-12-26 12:53 UTC, irfanuddinahmad commented on enterprise_data/api/v1/views/enterprise_learner.py
> +            queryset = queryset.filter(flex_group_uuid=group_uuid)
group_uuid__in=flex_group_uuids

2024-12-26 12:53 UTC, irfanuddinahmad commented on enterprise_data/api/v1/views/enterprise_learner.py
> +                flex_group_uuid=Subquery(
should be flex_group_uuids

2024-12-26 12:53 UTC, irfanuddinahmad commented on enterprise_data/models.py
> +    is_applies_to_all_contexts = models.BooleanField(default=False)
Note the table column types
`table_columns = [
  ['is_applies_to_all_contexts', 'boolean'],
  ['enterprise_customer_id', 'varchar(32)'],
  ['enterprise_group_name', 'varchar(255)'],
  ['enterprise_group_uuid', 'varchar(32)'],
  ['group_is_removed', 'boolean'],
  ['group_type', 'varchar(128)'],
  ['activated_at', 'datetime(6)'],
  ['enterprise_customer_user_id', 'int'],
  ['membership_is_removed', 'boolean'],
  ['membership_status', 'varchar(128)'],
  ['enterprise_group_membership_uuid', 'varchar(32)'],
]`

2024-12-30 07:34 UTC, omar-sarfraz commented on enterprise_data/api/v1/urls.py
> +        fr'^enterprise/(?P<enterprise_uuid>{UUID4_REGEX})/segments',
I discussed with @muhammad-ammar and we decided to create a generic API which should return both the groups and budgets for an enterprise, that's why I've named this url as segments.

2024-12-30 07:35 UTC, omar-sarfraz commented on enterprise_data/api/v1/views/enterprise_admin.py
> +    View for getting Group Memberships and Budgets information for an enterprise.
See this [reply](https://github.com/openedx/edx-enterprise-data/pull/550#discussion_r1899339776)

2024-12-30 07:36 UTC, omar-sarfraz commented on enterprise_data/api/v1/views/enterprise_admin.py
> +        budgets = EnterpriseSubsidyBudget.objects.filter(
See this [reply](https://github.com/openedx/edx-enterprise-data/pull/550#discussion_r1899339776)

2024-12-30 07:54 UTC, omar-sarfraz commented on enterprise_data/api/v1/views/enterprise_learner.py
> +                flex_group_uuid=Subquery(
As we are filtering based on `enterprise_customer_user_id` and `enterprise_group_uuid`, wouldn't the `Subquery` return a single row because we would have a single instance of enterprise customer user in a specified group?

2024-12-30 07:58 UTC, omar-sarfraz commented on enterprise_data/models.py
> +    is_applies_to_all_contexts = models.BooleanField(default=False)
Can you please help me with finding the mismatch between the **table column types** and the **django model**?

2025-01-13 07:17 UTC, irfanuddinahmad approved these changes
LGTM

2025-01-14 09:26 UTC, merged