Learner completed courses
openedx/edx-enterprise-data pull request #61
Opened 2018-09-07 10:44 UTC by mushtaqak

[ENT-1167](https://openedx.atlassian.net/browse/ENT-1167)

2018-09-10 11:32 UTC, mushtaqak commented
@georgebabey This is ready for your review. Thanks.

2018-09-10 12:42 UTC, muhammad-ammar requested changes
@mushtaqak I am done with first pass of the review. Let me know once feedback is addressed?

2018-09-10 12:42 UTC, muhammad-ammar commented on enterprise_data/api/v0/views.py
> +        ).values('user_email').annotate(completed_courses=Count('course_id')).order_by('user_email')
any idea why we need `order_by` here?

2018-09-10 12:42 UTC, muhammad-ammar commented on enterprise_data/api/v0/views.py
> +        self.ensure_data_exists(
this method call is exactly same like we already have in `EnterpriseEnrollmentsViewSet`?

2018-09-10 12:42 UTC, muhammad-ammar commented on enterprise_data/tests/test_views.py
> +        assert len(result) == 1
don't we need to verify the data to see if the correct data is returned?

2018-09-10 12:42 UTC, muhammad-ammar commented on enterprise_data/tests/test_views.py
> +        self.enterprise_api_client.return_value.get_with_access_to.return_value = {
this code is common for both the tests, can we move it to `setUp`?

2018-09-10 12:42 UTC, muhammad-ammar commented on enterprise_data/api/v0/serializers.py
> +    completed_courses = serializers.IntegerField()
what about making this `PositiveIntegerField`?

2018-09-11 07:29 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +        ).values('user_email').annotate(completed_courses=Count('course_id')).order_by('user_email')
I added it because I wanted to make sure we get results ordered by user email not any other arbitrary column. @georgebabey Now that I think of, is it ok we order by user email or we should order by learner completed course.

For the record, this is the example record we get.

user_email | course_completed
------------ | -------------
test_user@gmail.com | 5
test_user2@gmail.com | 7

2018-09-11 07:30 UTC, mushtaqak commented on enterprise_data/api/v0/serializers.py
> +    completed_courses = serializers.IntegerField()
It's a good suggestion, since we always get at-least one course completed in our serializer.

2018-09-11 07:38 UTC, mushtaqak commented on enterprise_data/api/v0/serializers.py
> +    completed_courses = serializers.IntegerField()
Actually there is no `PositiveIntegerField` serializer field 🙉

2018-09-11 07:50 UTC, mushtaqak commented on enterprise_data/tests/test_views.py
> +        assert len(result) == 1
Added data verification as well.

2018-09-11 08:59 UTC, muhammad-ammar approved these changes
👍

2018-09-11 14:15 UTC, christopappas approved these changes
Looks good to me

2018-09-12 12:42 UTC, mushtaqak commented
@georgebabey @zubair-arbi Is this good to merge ?

2018-09-12 12:49 UTC, merged