ENT-1185 - Update Course Catalog CSV flat file to have only one single header and a line of rows.
openedx/edx-enterprise-data pull request #62
Opened 2018-09-12 09:20 UTC by asadiqbal08

[ENT-1185](https://openedx.atlassian.net/browse/ENT-1185)

Update Course Catalog CSV flat file format to have only one single header and a line of rows.

#### NOTE: 
Implemented a suggested solution of putting all of the values as is into the column, even for simple arrays, in the form of JSON objects. This would also likely be the easiest to implement. In the example the column would have the possible value of:

> transcript_languages

`
 ['English', 'Hindi', 'Dutch', 'Chinese - Mandarin']  
`

2018-09-12 09:41 UTC, zubair-arbi commented on enterprise_reporting/reporter.py
> +                    writer.writerow(flatten_dict(grouped_items[0], target='key'))
Can you please add a comment mentioning that we are doing this to add column headers for one time only?

2018-09-12 09:42 UTC, zubair-arbi approved these changes
Just one small suggestion otherwise change looks good 👍

2018-09-12 13:56 UTC, georgebabey commented
I don't believe this will work if the first course does not have some fields, but other courses do. For example course_runs for 8647cd55-7fea-4b29-b4de-e014fd4f030a has multiple seat_types, transcript_languages,etc which were being serialized to 1 per column. This leads to inconsistent # of columns, which is why the odd format was chosen in the first place.

![screen shot 2018-09-12 at 9 53 43 am](https://user-images.githubusercontent.com/1643389/45429723-dbccec80-b671-11e8-8be1-e5436bc1c00f.png)

2018-09-12 16:26 UTC, georgebabey requested changes
Discussion around formatting in the JIRA, but I believe this will need to be updated

2018-09-17 09:04 UTC, saleem-latif approved these changes
Looks Good 👍

2018-09-18 12:44 UTC, georgebabey commented on enterprise_reporting/reporter.py
>                      writer.writerow([])
This is adding an extra line between each row

2018-09-18 12:47 UTC, georgebabey commented
This looks good, just a couple suggestions:
- For empty lists we should probably just output an empty string rather than filling it up with []
- If only one item in a list, output that item instead of the list. (Example: Language is usually just set to one language even though it supports multiple)

2018-09-18 13:54 UTC, asadiqbal08 commented
@georgebabey, I looked around your suggestions. Good ones and I am OK with 
--> "For empty lists we should probably just output an empty string rather than filling it up with []" 
But I think we should keep the data as a list even if there is one or more items in list. 

I am just thinking about the consistency b/w data representation in CSV files . 

Some **transcript_languages** are just <LIST> while some rows have strings OR the possibility of having the single item is another DataType e.g. dict etc. 

Suggest ?? OR as you like, I will update the PR accordingly.

2018-09-19 09:50 UTC, asadiqbal08 commented on enterprise_reporting/reporter.py
>                      writer.writerow([])
Ok. I will remove it.

2018-09-19 12:37 UTC, georgebabey commented
@asadiqbal08 Yeah, consistency makes sense then. Lets keep it as a list

2018-09-19 12:38 UTC, georgebabey approved these changes
Just remove the extra rows and this is good to go 👍

2018-09-24 09:49 UTC, merged