Learner activity details
openedx/edx-enterprise-data pull request #64
Opened 2018-09-13 13:51 UTC by mushtaqak

[ENT-1166](https://openedx.atlassian.net/browse/ENT-1166)

2018-09-18 11:01 UTC, zubair-arbi commented on enterprise_data/api/v0/views.py
> +    while one_month_earlier.month == original_date.month or one_month_earlier.day > original_date.day:
Maybe we can shorten this logic and make it more readable: https://stackoverflow.com/questions/9724906/python-date-of-the-previous-month

2018-09-18 11:01 UTC, zubair-arbi commented on enterprise_data/api/v0/views.py
> +        past_month_date = subtract_one_month(date.today())
Maybe also name the method `subtract_one_month` to `past_month_date` for clarity

2018-09-18 12:47 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +    while one_month_earlier.month == original_date.month or one_month_earlier.day > original_date.day:
This was written before. I just moved it outside the ViewSet.

2018-09-18 12:47 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +        past_month_date = subtract_one_month(date.today())
Ok.

2018-09-19 10:27 UTC, georgebabey commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(last_activity_date__gte=last_activity_date)
Without the distinct here, if an active learner has multiple enrollments won't we get multiple results?

2018-09-19 10:29 UTC, georgebabey commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(last_activity_date__lte=last_activity_date)
I believe we also want `filter_distinct_learners` here as well

2018-09-19 10:30 UTC, georgebabey commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(
And distinct here..

2018-09-19 10:31 UTC, georgebabey requested changes
Overall looks good, just have some questions regarding using the `filter_distinct_learners` in additional places to avoid multiple rows for multiple enrollments.

2018-09-19 10:46 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(last_activity_date__gte=last_activity_date)
Actually the ticket says:
> Current columns filtered by learners active in past week
There may be duplicate learners if they were in active than more than 1 course

2018-09-19 10:46 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(last_activity_date__lte=last_activity_date)
`filter_distinct_learners` actually modifies the queryset since it only returns `enterprise_user_id` due to `queryset.values_list('enterprise_user_id', flat=True).distinct()`

2018-09-19 10:54 UTC, georgebabey commented on enterprise_data/api/v0/views.py
> +        return queryset.filter(last_activity_date__gte=last_activity_date)
Ah, got it, so its actually returning enrollment rows, not learners. got it. 👍

2018-09-19 10:57 UTC, georgebabey approved these changes
Sorry about the confusion on distinct. Rereading the ticket you are correct, the intent is to return enrollment records, not learners, so distinct is not needed.

:shipit:

2018-09-19 12:20 UTC, mushtaqak commented on enterprise_data/api/v0/views.py
> +        past_month_date = subtract_one_month(date.today())
@zubair-arbi I think I will pass on this one as well. Since, in test we may need to get a date for two or three months back or in future we can set a differnt timeline for user activity as well. Let me know if you want to change this as well.

2018-09-24 10:04 UTC, mushtaqak commented on CHANGELOG.rst
> +* Update the course catalog CSV flat file to have only one single header and a line of rows in JSON form.
cc: @asadiqbal08

2018-09-24 10:11 UTC, merged