ENT-1189 Add enterprise learner course completion count
openedx/edx-enterprise-data pull request #66
Opened 2018-09-26 08:14 UTC by zubair-arbi

[ENT-1189](https://openedx.atlassian.net/browse/ENT-1189)

Allow for extra field `course_completion_count` to be added to response when "extra_fields" query param is provided that includes the text "`course_completion_count`".

Expected URL for ENT-1189:
http://localhost:18000/enterprise/api/v0/enterprise/72416e52-8c77-4860-9584-15e5b06220fb/users/?extra_fields=enrollment_count+course_completion_count&has_enrollments=true&active_courses=false&page_size=50

2018-09-27 09:20 UTC, mushtaqak approved these changes
One question otherwise looks good.

2018-09-27 09:20 UTC, mushtaqak commented on enterprise_data/api/v0/serializers.py
> +            if 'course_completion_count' in extra_fields:
Should we not have elif statement since `extra_fields` key can only contain single value.

2018-09-27 09:33 UTC, mushtaqak requested changes

2018-09-27 09:33 UTC, mushtaqak commented on enterprise_data/tests/test_views.py
> +        params = {'extra_fields': 'course_completion_count', }
It's a bit confusing we are expecting a list in `to_representation` but here we can only pass single value.

2018-09-27 09:33 UTC, mushtaqak commented on enterprise_data/tests/test_views.py
> +        params = {'extra_fields': 'course_completion_count', }
Also can we have a test where both `extra_fields` are used? and what will be our expectations, whom would we prioritize ?

2018-09-27 09:34 UTC, zubair-arbi commented on enterprise_data/api/v0/serializers.py
> +            if 'course_completion_count' in extra_fields:
According to my understanding as name says `extra_fields` can contain multiple fields so the value can be `enrollment_count+course_completion_count`.

2018-09-27 09:43 UTC, zubair-arbi commented on enterprise_data/tests/test_views.py
> +        params = {'extra_fields': 'course_completion_count', }
I will add a test for multiple fields.
We don't need to prioritize, all specified fields in `extra_fields` will be returned in the response.

2018-10-03 07:52 UTC, mushtaqak commented on enterprise_data/api/v0/serializers.py
> +            if 'course_completion_count' in extra_fields:
According to the feedback on https://github.com/edx/edx-portal/pull/79. we will be getting `'extra_fields'` list as follow:
```python
request.query_params.getlist('extra_fields')
```

2018-10-04 12:23 UTC, zubair-arbi commented
@mushtaqak I have addressed your feedback. Please have another look.

2018-10-05 10:18 UTC, mushtaqak approved these changes
Looks good 👍

2018-10-05 10:31 UTC, zubair-arbi commented
@adamstankiewicz @georgebabey please review so that I can merge this backend change.

2018-10-05 12:27 UTC, zubair-arbi commented
We need this PR to merge first for enterprise portal.

2018-10-05 14:10 UTC, adamstankiewicz approved these changes
Looks good. Just one small update in one of the test comments. After that, should be good to go!

2018-10-05 14:10 UTC, adamstankiewicz commented on enterprise_data/tests/test_views.py
> +        if value "enrollment_count+course_completion_count" is specified in
Might want to update this comment as the `extra_fields` value is no longer `enrollment_count+course_completion_count`.

2018-10-08 08:39 UTC, merged