ENT 1273 ability to PGP encrypt files
openedx/edx-enterprise-data pull request #73
Opened 2018-10-18 13:11 UTC by irfanuddinahmad

JIRA https://openedx.atlassian.net/browse/ENT-1273

2018-10-22 09:18 UTC, zubair-arbi requested changes

2018-10-22 09:18 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +        except PGPDecryptionError:
Please remove exception handling code here in the test.

2018-10-22 09:18 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +    if key:
We are taking key as required parameter then checking here if key is available is not necessary.

2018-10-22 09:18 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +def compress_and_encrypt(files, password, key):
rename the key name to something like `pgpy_key` and make it opitonal
```python
def compress_and_encrypt(files, password, pgpy_key=None)
```

2018-10-22 09:18 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +        rsa_pub, _ = pgpy.PGPKey.from_blob(key)
Its better to move the logic of pgp zip file creation to a separate helper method, e.g. `_get_pgp_encrypted_zip_file(compressed_zip_file, pgp_key)`

2018-10-22 09:18 UTC, zubair-arbi commented on requirements/base.in
> +PGPy==0.4.3                             # Required for Enterprise Reporting
I think we don't need to pip the version of this library and also add this library in test.in

2018-10-22 09:18 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +    PubKeyAlgorithm, KeyFlags, HashAlgorithm,
use `isort` for ordering these imports

2018-10-22 09:37 UTC, zubair-arbi requested changes

2018-10-22 09:37 UTC, zubair-arbi commented on enterprise_reporting/delivery_method.py
> +        self.encryption_pgp_key = reporting_config['encryption_pgp_key']
`encryption_pgp_key` -> `pgp_encryption_key`

2018-10-22 12:01 UTC, irfanuddinahmad commented on enterprise_reporting/tests/test_utils.py
> +        except PGPDecryptionError:
The test passes when the PGPDecryptionError does 'not' appear

2018-10-22 12:07 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +        except PGPDecryptionError:
use the `assertRaises` syntax for validating raised exceptions.
```python
with self.assertRaises(PGPDecryptionError):
    key.decrypt(message)
```

2018-10-22 12:21 UTC, irfanuddinahmad commented on enterprise_reporting/tests/test_utils.py
> +        except PGPDecryptionError:
We need a assertNotRaises ...

2018-10-23 08:25 UTC, zubair-arbi requested changes

2018-10-23 08:25 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +        key1 = self.pgpy_create_key('JohnDoe')
nit: there is no other key being used in this test so lets name it `pgp_key`

2018-10-23 08:25 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +        with self.assertRaises(PGPError):
Ideally we should verify the correct flow here as the test name is `test_encryption` (also the descrytion of the test says about correct encryption/decryption), maybe we can have a separate test for verifying that decryption of invalid pgp_message raises exception, e.g `test_invalid_pgp_message`

2018-10-23 08:25 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +        rsa_pub, _ = pgpy.PGPKey.from_blob(pgp_key)
we still need to move this logic to separate helper method.

2018-10-23 08:38 UTC, irfanuddinahmad commented on enterprise_reporting/utils.py
> +        rsa_pub, _ = pgpy.PGPKey.from_blob(pgp_key)
> we still need to move this logic to separate helper method.

can you be a bit more specific since this code seems to be quite cohesive

2018-10-23 08:38 UTC, irfanuddinahmad commented on enterprise_reporting/tests/test_utils.py
> +        with self.assertRaises(PGPError):
> Ideally we should verify the correct flow here as the test name is `test_encryption` (also the descrytion of the test says about correct encryption/decryption), maybe we can have a separate test for verifying that decryption of invalid pgp_message raises exception, e.g `test_invalid_pgp_message`

The test for a correct encryption is a correct decryption ...

2018-10-23 09:24 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +        rsa_pub, _ = pgpy.PGPKey.from_blob(pgp_key)
Its better to move the logic of pgp zip file creation to a separate helper method, e.g. _get_pgp_encrypted_zip_file(compressed_zip_file, pgp_key). This will result in increased readability.

2018-10-23 09:30 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +        with self.assertRaises(PGPError):
The logic in code looks correct. Just need to update the docstring of test to reflect what its doin. Something like: 

```python
This test validates we are able to decrypt an encrypted pgp message 
with valid key and decrypting the encrypted pgp message with invalid 
key results in exception `PGPError`.
```

2018-10-23 15:05 UTC, brittneyexline reviewed
just a few small things, but generally this looks good.

2018-10-23 15:05 UTC, brittneyexline commented on enterprise_reporting/utils.py
> +        return pgpfile
Couple of things here:
It seems like we intend to either send a password protected zip or a pgp encrypted file. I agree with Zubair that restructuring the code would make this clearer. We could even go so far as to enforce in your edx-enterprise PR where the configuration field is added that only one of zip password or pgp key should be set.
Does it matter what order of operations we pgp encrypt vs. zip the file? It is more intuitive to me to pgp encrypt the file and then zip it, but I'm not sure it matters.

2018-10-23 15:05 UTC, brittneyexline commented on requirements/test.in
> +pgpy
nit: missing new line

2018-10-23 15:05 UTC, brittneyexline commented on requirements/travis.in
> +pgpy
nit: missing new line

2018-10-24 12:25 UTC, irfanuddinahmad commented on enterprise_reporting/utils.py
> +        return pgpfile
Thanks. I have incorporated most of the feedback. It may be easier for the client to decrypt a zip file rather than individually decrypt many files. Also, we may have a future requirement for both the password and encryption (belt and suspenders!)

2018-10-24 12:56 UTC, zubair-arbi commented on enterprise_reporting/utils.py
> +        Given file(s) and a password, create a zip file. Return the new filename.
nit: remove extra indentation

2018-10-24 12:57 UTC, zubair-arbi commented on enterprise_reporting/tests/test_utils.py
> +                    compression=[CompressionAlgorithm.ZLIB, CompressionAlgorithm.BZ2, CompressionAlgorithm.ZIP,
nit: please remove all the extra attributes while adding key.

2018-10-24 12:58 UTC, zubair-arbi approved these changes
A few suggestions otherwise LGTM 👍

2018-10-24 12:59 UTC, irfanuddinahmad commented on enterprise_reporting/tests/test_utils.py
> +                    compression=[CompressionAlgorithm.ZLIB, CompressionAlgorithm.BZ2, CompressionAlgorithm.ZIP,
> nit: please remove all the extra attributes while adding key.

PGPy seems to want these on the user

2018-10-25 14:39 UTC, brittneyexline approved these changes

2018-10-25 14:48 UTC, merged