ENT-1244 | External Resource Link Report
openedx/edx-enterprise-data pull request #90
Opened 2018-11-27 19:46 UTC by christopappas

Close to what I want it to be. Please ask any questions that come to mind.

Notes:
- `py2neo` is very convenient, but added a few [most likely unimpactful, yet never the less more] dependencies.
- The first pass at filtering links comes down to knocking out images and obvious edx extensions.
- Needs tests? Yep. I think I have another PR that adds the `enterprise_reporting` app to the tests which will be needed if we want this code to have tests that run with `make validate`.

2018-11-28 16:00 UTC, brittneyexline reviewed
looks good overall! i would say next steps would be adding some logging and error handling, and moving some of the strings you have to constants. i also remember you saying that coursegraph only gets updated once per week, so if someone runs this on demand, should we consider having it send a file that was written to disk by a previous run if available to avoid hitting coursegraph again?

2018-11-28 16:13 UTC, georgebabey requested changes
Looks good, just a few minor suggestions

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +    csv_string = u'Course Key\tExternal Links\n'
Should we be using commas here instead of a tab-delimited csv? And if so we'll need to escape the commas in the links

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +        if (not link.lower().endswith('.pdf"') and
I think we should not exclude .pdf, as there may be external pdfs needed for the course.

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +            not '.edx.com' in link)
Are there really edx.com links? 😕

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +    body = '''Dear Customer Support,
s/Support/Success/

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +    to_email = 'someEmail@edx.org' #change me to param
Don't forget these todos!

2018-11-28 16:13 UTC, georgebabey commented on enterprise_reporting/external_resource_link_report.py
> +                "https://studio.edx.org/container/" + h.location as link
Looks like you're only using `course_key` and `data` so you could remove `link` (which is also confusing since links above refers to external links, but this is a link to the course.

2018-11-29 16:41 UTC, christopappas commented on enterprise_reporting/external_resource_link_report.py
> +    csv_string = u'Course Key\tExternal Links\n'
I admit, tabs are my delimiter personal preference for creating spreadsheets, and I can confirm it opens in excel alright (also prints nicely!). I'm happy to change if you think it should be though

2018-11-29 16:41 UTC, christopappas commented on enterprise_reporting/external_resource_link_report.py
> +        if (not link.lower().endswith('.pdf"') and
Okay, can remove this

2018-11-29 16:51 UTC, christopappas commented on enterprise_reporting/external_resource_link_report.py
> +            not '.edx.com' in link)
Did another check. apparently not. i could have sworn I saw something earlier on in my investigation. I'll remove this as it is probably unnecessary

2018-11-29 16:52 UTC, christopappas commented on enterprise_reporting/external_resource_link_report.py
> +    body = '''Dear Customer Support,
well sed. will change

2018-11-29 16:53 UTC, christopappas commented on enterprise_reporting/external_resource_link_report.py
> +                "https://studio.edx.org/container/" + h.location as link
will do

2018-11-30 20:20 UTC, brianhw commented
If you're interested in generating output suitable for Excel, you might want to consider using the "csv" package included in Python.   In particular, I understand they have a dialect='excel' option for the csv output that would handle decisions about delimiters and escaping and all that.

2018-11-30 20:35 UTC, christopappas commented
@brianhw That is a good recommendation. I ended up going with a custom string handling solution as the consumers of this report wanted some special whitespace formatting. It is a csv insofar that the actual column delimiters are commas (with quotes being used to escape any commas in titles), but the desire was for this report potentially to be showed to customers as-is, and therefore, was desired to look as though it was "pretty printed" to some extent

If I need to make further modifications to make this more like a standard CSV, I will certainly give the csv package a whirl 👍

2018-12-03 15:27 UTC, georgebabey approved these changes

2018-12-03 17:08 UTC, merged